# Generated by Django 5.0.6 on 2024-06-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_is_flashsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contact_details',
            field=models.CharField(default=799650551, max_length=75),
            preserve_default=False,
        ),
    ]
